# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20170630_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
