# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20170703_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('thing', models.CharField(max_length=264)),
            ],
        ),
    ]
