# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(default=None, upload_to='user_img/'),
        ),
    ]
