# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_auto_20170704_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImageUpload',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='category',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
