# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_auto_20170715_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='camera',
            field=models.CharField(default='debug', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='date',
            field=models.DateField(default='0000/00/00', verbose_name='Date (YYYY/MM/DD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='location',
            field=models.CharField(default='debug', max_length=100),
            preserve_default=False,
        ),
    ]
