# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_auto_20170716_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='date',
        ),
    ]
