# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_remove_imageupload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='date',
            field=models.DateField(default=0, verbose_name='Date (YYYY-MM-DD)'),
            preserve_default=False,
        ),
    ]
