# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_auto_20170716_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='date',
            field=models.DateField(default=datetime.date, verbose_name='Date (YYYY-MM-DD)'),
        ),
    ]
