# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_auto_20170717_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='date',
            field=models.DateField(default='0000-00-00', verbose_name='Date (YYYY-MM-DD)'),
        ),
    ]
