# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_auto_20170717_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=100)),
                ('msg', models.TextField(max_length=1000)),
            ],
        ),
    ]
