# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0021_emailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_handle',
            field=models.CharField(default='handle', max_length=100, verbose_name='Facbeook name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ig_handle',
            field=models.CharField(default='handle', max_length=100, verbose_name='Instagram handle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tw_handle',
            field=models.CharField(default='handle', max_length=100, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='emailrequest',
            name='msg',
            field=models.TextField(max_length=1000, verbose_name='Message (be nice)'),
        ),
        migrations.AlterField(
            model_name='emailrequest',
            name='sender',
            field=models.EmailField(max_length=254, verbose_name='Your e-mail'),
        ),
        migrations.AlterField(
            model_name='emailrequest',
            name='sub',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fb',
            field=models.URLField(verbose_name='Facebook URL'),
        ),
    ]
