# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0022_auto_20170717_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(max_length=3000, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fb_handle',
            field=models.CharField(default='handle', max_length=100, verbose_name='Facebook name'),
        ),
    ]
